"""add subject to ticket model

Revision ID: f0c930bf9c47
Revises: e22b6d070ebb
Create Date: 2025-01-17 14:32:15.847546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0c930bf9c47'
down_revision: Union[str, None] = 'e22b6d070ebb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('subject', sa.String(), nullable=True))
    # ### end Alembic commands ###
    op.execute("UPDATE tickets SET subject = 'Default subject' WHERE subject IS NULL")
    op.alter_column('tickets', 'subject', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'subject')
    # ### end Alembic commands ###
